### PR TITLE
add function to get all legal moves for a specific square

### PR DESCRIPTION
**Pull request by RoastBeefer00**
I added a function to get the psuedolegal  moves of a specific square and then made the function that gets ALL of them use that.  This will be useful to someone like me who wants to make a chess game and wants to be able to easily see all legal moves for a specific piece

### CODE REVIEW

**Comment by prawnydagrate** [comment]
Hi, I'd like to know more about your objective, if you don't mind. Does your game need the **legal** moves from a specific square, or the **pseudolegal** moves from a specific square?

**Comment by RoastBeefer00** [comment]
I think it would need both but the other half would still need to be written.  Having the ability to calculate for a single square would be very useful and much faster than calculating the whole board and then filtering.  If you don't want this implemented, please feel free to deny the PR

**Comment by prawnydagrate** [comment]
Nono I think this is a great idea. Is it okay if I go in and change some of the code though? I feel like this function would be more appropriate on the `Position` struct (only) than also the `Board` struct, because the `Board` struct is supposed to represent an actual game while the `Position` struct gives you functionalities specific to the chess position on the board

**Comment by RoastBeefer00** [comment]
It's your repo, please feel free to change whatever you like

**Comment by prawnydagrate** [comment]
Hi, sorry I took so long. I had back-to-back exams everyday and today was the last one, marking the start of a three-day break before the next.

Could you check if this is fine?

**Pull request merged**
